return {
	siegemega = {
		name                   = "Gilgamesh",
		description            = "SuperHeavy Assault-Riot",
		acceleration           = 0.15,
		brakeRate              = 0.48,
		metalCost              = 2400,
		buildPic               = "siegemega.png",
		canAttack              = true,
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		canManualFire          = false,
		category               = "LAND",
		collisionVolumeOffsets = "0 0 0",
		collisionVolumeScales  = "50 85 50",
		collisionVolumeTest    = 1,
		collisionVolumeType    = "CylY",
		corpse                 = "DEAD",
		
		customParams           = {
			--canjump            = 1,
			--jump_range         = 750,
			--jump_speed         = 9,
			--jump_reload        = 15,
			--jump_from_midair   = 1,
			soundok = "heavy_bot_move",
			soundselect = "bot_select",

	normaltex = [[unittextures/atlas_normal.dds]],
		},
		
		explodeAs              = "ESTOR_BUILDING",
		footprintX             = 4,
		footprintZ             = 4,
		iconType               = "siegestrider2",
		idleAutoHeal           = 25,
		idleTime               = 450, -- 15s
		leaveTracks            = true,
		health              = 12000,
		maxSlope               = 36,
		speed                  = 45,
		maxWaterDepth          = 36,
		minCloakDistance       = 75,
		movementClass          = "AKBOT4",
		noChaseCategory        = "TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET",
		objectName             = "legeheatraymech.s3o",
		script                 = "siegemega.lua",
		selfDestructAs         = "ESTOR_BUILDING",
		sfxtypes               = {
			explosiongenerators = {
				"custom:THUDMUZZLE",
				"custom:THUDSHELLS",
				"custom:THUDDUST",
				"custom:STORMMUZZLE",
				"custom:VINDIBACK",
			},
		},
		sightDistance          = 650,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ComTrack",
		trackWidth             = 32,
		turnRate               = 640,
		upright                = true,
		
		
		weapons                = {
					-- {
				-- def                = "VACUUM",
				-- badTargetCategory  = "FIXEDWING",
				-- onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			-- },      
	    {
      def                = [[PLASMA]],
      badTargetCategory  = [[GUNSHIP]],
      onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP]],
    },
	
			--{
				--def                = "LANDING",
				--mainDir            = "1 0 0",
				--maxAngleDif        = 0,
				--onlyTargetCategory = "NULL",
			--},
			--{
				--def                = "VACUUM",
				--badTargetCategory  = "FIXEDWING",
				--onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			--},      

		},
		
		 weaponDefs             = {
		
    PLASMA = {
      name                    = [[Very Heavy Plasma Cannon]],
      accuracy                = 500,
      areaOfEffect            = 156,
      avoidFeature            = false,
      cegTag                  = [[vulcanfxsmall]],
      craterBoost             = 0.25,
      craterMult              = 0.5,

      customParams            = {
        gatherradius     = [[220]],
        smoothradius     = [[100]],
        smoothmult       = [[0.5]],
        movestructures   = [[0.25]],
        force_ignore_ground = "1",
        
        light_color = [[2.4 1.5 0.6]],
      },
      
      damage                  = {
        default = 600.4,
      },

      explosionGenerator      = [[custom:lrpc_explsmall]],
      fireTolerance           = 2520, -- 10 degrees
      impulseBoost            = 0.5,
      impulseFactor           = 0.2,
      interceptedByShieldType = 1,
      noSelfDamage            = true,
      range                   = 500,
      reloadtime              = 2,
      soundHit                = [[weapon/cannon/lrpc_hit]],
      soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
      turret                  = true,
	  size                    = 1,
      weaponType              = [[Cannon]],
      weaponVelocity          = 500,
    },


			-- VACUUM = {
				-- name                    = "Vacuum Gun",
				-- areaOfEffect            = 400,
				-- commandfire             = true,
				-- avoidFeature            = false,
				-- avoidFriendly           = false,
				-- burnblow                = false,
				-- craterBoost             = 0,
				-- craterMult              = 0,
				-- cegtag                  = "energeticblackhole_trail",
				-- customParams            = {
					-- light_color = "0 .8 1 .1",
					-- light_radius = 500,
					-- lups_explodelife = 1.0,
					-- lups_explodespeed = 0.5,
					-- light_radius = 80,
					-- blastwave_size = 200,
					-- blastwave_impulse = -3.5,
					-- blastwave_speed = -6.6,
					-- blastwave_life = 30,
					-- blastwave_lossfactor = 0.85,
					-- blastwave_damage = 40,
				-- },

				-- damage                  = {
					-- default = 500, --make it not suck vs shields
				-- },

				-- explosionGenerator      = "custom:energeticblackhole_112", -- technically it's 400, but i can't be assed to rename.
				-- explosionSpeed          = 50,
				-- impulseBoost            = 150,
				-- impulseFactor           = -2.5,
				-- intensity               = 0.9,
				-- interceptedByShieldType = 1,
				-- myGravity               = 0.1,
				-- projectiles             = 1,
				-- range                   = 500,
				-- reloadtime              = 20,
				-- rgbColor                = "0.05 0.05 0.05",
				-- size                    = 3,
				-- soundHit                = "weapon/impacts/impulsewave1",
				-- soundStart              = "weapon/cannon/commblackhole_fire",
				-- soundStartVolume        = 100,
				-- soundHitVolume          = 100,
				-- turret                  = true,
				-- weaponType              = "Cannon",
				-- weaponVelocity          = 550,
				-- waterweapon             = true,
			-- },
			-- LANDING = {
				-- name                    = "Jump Impact",
				-- areaOfEffect            = 300,
				-- canattackground         = false,
				-- craterBoost             = 4,
				-- craterMult              = 6,
				-- damage                  = {
					-- default = 2500,
				-- },
				-- edgeEffectiveness       = 0,
				-- explosionGenerator      = "custom:FLASH64",
				-- impulseBoost            = 1,
				-- impulseFactor           = 0.8,
				-- interceptedByShieldType = 1,
				-- noSelfDamage            = true,
				-- range                   = 5,
				-- reloadtime              = 20,
				-- soundHit                = "krog_stomp",
				-- soundStart              = "krog_stomp",
				-- soundStartVolume        = 3,
				-- startsmoke              = "1",
				-- turret                  = false,
				-- weaponType              = "Cannon",
				-- weaponVelocity          = 5,
				-- waterweapon             = true,
			-- },    
		},
		featureDefs            = {
			DEAD      = {
				description      = "Wreckage",
				blocking         = true,
				category         = "corpses",
				damage           = 6400,
				energy           = 0,
				featureDead      = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintX       = 4,
				footprintZ       = 4,
				height           = "20",
				hitdensity       = "100",
				metal            = 1200,
				object           = "legeheatraymech_dead.s3o",
				reclaimable      = true,
				reclaimTime      = 1200,
				seqnamereclamate = "TREE1RECLAMATE",
				world            = "All Worlds",
			},
			HEAP      = {
				description      = "Debris",
				blocking         = false,
				category         = "heaps",
				damage           = 6400,
				energy           = 0,
				featurereclamate = "SMUDGE01",
				footprintX       = 2,
				footprintZ       = 2,
				hitdensity       = "100",
				metal            = 600,
				object           = "debris2x2c.s3o",
				reclaimable      = true,
				reclaimTime      = 600,
				seqnamereclamate = "TREE1RECLAMATE",
				world            = "All Worlds",
			},
		},
	}
}