return {
	siegestrider = {
		name                   = "Atlas",
		description            = "Siege Assault Raider",
		acceleration           = 0.14,
		brakeRate              = 0.28,
		metalCost              = 1800,
		buildPic               = "siegestrider.png",
		canAttack              = true,
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		canManualFire          = false,
		category               = "LAND",
		collisionVolumeOffsets = "0 0 0",
		collisionVolumeScales  = "50 85 50",
		collisionVolumeTest    = 1,
		collisionVolumeType    = "CylY",
		corpse                 = "DEAD",
		customParams           = {
			--canjump            = 1,
			--jump_range         = 750,
			--jump_speed         = 9,
			--jump_reload        = 15,
			--jump_from_midair   = 1,
			soundok = "heavy_bot_move",
			soundselect = "bot_select",
				heat_per_shot  = 0.025, -- Heat is always a number between 0 and 1
    heat_decay     = 1/6, -- Per second
    heat_max_slow  = 0.50,
    heat_initial   = 0,
	normaltex = [[unittextures/atlas_normal.dds]],
		},
		explodeAs              = "ESTOR_BUILDING",
		footprintX             = 4,
		footprintZ             = 4,
		iconType               = "siegestrider",
		idleAutoHeal           = 15,
		idleTime               = 450, -- 15s
		leaveTracks            = true,
		health              = 7600,
		maxSlope               = 36,
		speed                  = 75,
		maxWaterDepth          = 36,
		minCloakDistance       = 75,
		movementClass          = "AKBOT4",
		noChaseCategory        = "TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET",
		objectName             = "legjav.s3o",
		script                 = "siegejav.lua",
		selfDestructAs         = "ESTOR_BUILDING",
		sfxtypes               = {
			explosiongenerators = {
				"custom:THUDMUZZLE",
				"custom:THUDSHELLS",
				"custom:THUDDUST",
				"custom:STORMMUZZLE",
				"custom:VINDIBACK",
			},
		},
		sightDistance          = 700,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ComTrack",
		trackWidth             = 32,
		turnRate               = 620,
		upright                = true,
		
		
		weapons                = {
    {
      def                = [[WARRIOR_WEAPON]],
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
    },
    -- {
      -- def                = [[LASER]],
      
      -- onlyTargetCategory = [[GUNSHIP FIXEDWING]],
    -- },
			--{
				--def                = "LANDING",
				--mainDir            = "1 0 0",
				--maxAngleDif        = 0,
				--onlyTargetCategory = "NULL",
			--},
			--{
				--def                = "VACUUM",
				--badTargetCategory  = "FIXEDWING",
				--onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			--},      

		},
		
		 weaponDefs             = {
		
		    WARRIOR_WEAPON = {
      name                    = [[Heavy Pulse MG]],
      accuracy                = 420,
      alphaDecay              = 0.7,
      areaOfEffect            = 66,
      burnblow                = true,
      cegTag                  = [[hmg_trail_light]],
      craterBoost             = 0.15,
      craterMult              = 0.3,

      customParams        = {
        reaim_time = 1, -- noticeable twitching otherwise due to huge turnrates
        light_camera_height = 1600,
        light_color = [[0.8 0.76 0.38]],
        light_radius = 150,
        force_ignore_ground = [[1]],
      },

      damage                  = {
        default = 40,
        planes  = 40,
      },

      edgeEffectiveness       = 0.5,
      explosionGenerator      = [[custom:EMG_HIT_HE]],
      firestarter             = 70,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      intensity               = 0.7,
      interceptedByShieldType = 1,
      noSelfDamage            = true,
      range                   = 350,
      reloadtime              = 0.066,
      rgbColor                = [[1 0.55 0.4]],
      separation              = 1.6,
      soundHit                = [[weapon/cannon/emg_hit]],
      soundStart              = [[weapon/heavy_emg]],
      stages                  = 10,
      turret                  = true,
      weaponType              = [[Cannon]],
      weaponVelocity          = 600,
    },
			-- LASER = {
      -- name                    = [[Laser Blaster]],
      -- areaOfEffect            = 8,
      -- cegTag                  = [[laser_cannon_trail_thin]],
      -- coreThickness           = 0.5,
      -- craterBoost             = 0,
      -- craterMult              = 0,

      -- customParams        = {
        -- light_camera_height = 1200,
        -- light_radius = 120,
      -- },
      
      -- damage                  = {
        -- default = 9.48,
      -- },

      -- duration                = 0.02,
      -- explosionGenerator      = [[custom:BEAMWEAPON_HIT_RED]],
      -- fireStarter             = 50,
      -- heightMod               = 1,
      -- impactOnly              = true,
      -- impulseBoost            = 0,
      -- impulseFactor           = 0.4,
      -- interceptedByShieldType = 1,
      -- leadLimit               = 0,
      -- noSelfDamage            = true,
      -- range                   = 800,
      -- reloadtime              = 0.1,
      -- rgbColor                = [[1 0 0]],
      -- soundHit                = [[weapon/laser/lasercannon_hit]],
      -- soundStart              = [[weapon/laser/small_laser_fire2]],
      -- soundTrigger            = true,
      -- thickness               = 2.55,
	  -- canattackground         = false,
      -- tolerance               = 14000,
      -- turret                  = true,
      -- weaponType              = [[LaserCannon]],
      -- weaponVelocity          = 1200,
    -- },
			--VACUUM = {
				--name                    = "Vacuum Gun",
				--areaOfEffect            = 400,
				--commandfire             = true,
				--avoidFeature            = false,
				--avoidFriendly           = false,
				--burnblow                = false,
				--craterBoost             = 0,
				--craterMult              = 0,
				--cegtag                  = "energeticblackhole_trail",
				--customParams            = {
				--	light_color = "0 .8 1 .1",
				--	light_radius = 500,
				--	lups_explodelife = 1.0,
				--	lups_explodespeed = 0.5,
				--	light_radius = 80,
					--blastwave_size = 200,
				--	blastwave_impulse = -3.5,
					--blastwave_speed = -6.6,
					--blastwave_life = 30,
					--blastwave_lossfactor = 0.85,
					--blastwave_damage = 40,
				--},

				--damage                  = {
					--default = 500, --make it not suck vs shields
				--},

				--explosionGenerator      = "custom:energeticblackhole_112", -- technically it's 400, but i can't be assed to rename.
				--explosionSpeed          = 50,
				--impulseBoost            = 150,
				--impulseFactor           = -2.5,
				--intensity               = 0.9,
				--interceptedByShieldType = 1,
				--myGravity               = 0.1,
				--projectiles             = 1,
				--range                   = 500,
				--reloadtime              = 20,
				--rgbColor                = "0.05 0.05 0.05",
				--size                    = 3,
				--soundHit                = "weapon/impacts/impulsewave1",
				--soundStart              = "weapon/cannon/commblackhole_fire",
				--soundStartVolume        = 100,
				--soundHitVolume          = 100,
				--turret                  = true,
				--weaponType              = "Cannon",
				--weaponVelocity          = 550,
				--waterweapon             = true,
			--},
			--LANDING = {
				--name                    = "Jump Impact",
				--areaOfEffect            = 300,
				--canattackground         = false,
				--craterBoost             = 4,
				--craterMult              = 6,
				--damage                  = {
				--	default = 2500,
				--},
				--edgeEffectiveness       = 0,
				--explosionGenerator      = "custom:FLASH64",
				--impulseBoost            = 1,
				--impulseFactor           = 0.8,
				--interceptedByShieldType = 1,
				--noSelfDamage            = true,
				--range                   = 5,
				--reloadtime              = 20,
				--soundHit                = "krog_stomp",
				--soundStart              = "krog_stomp",
				--soundStartVolume        = 3,
				--startsmoke              = "1",
				--turret                  = false,
				--weaponType              = "Cannon",
				--weaponVelocity          = 5,
				--waterweapon             = true,
			--},    
		},
		featureDefs            = {
			DEAD      = {
				description      = "Wreckage",
				blocking         = true,
				category         = "corpses",
				damage           = 6400,
				energy           = 0,
				featureDead      = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintX       = 4,
				footprintZ       = 4,
				height           = "20",
				hitdensity       = "100",
				metal            = 1200,
				object           = "legjav_dead.s3o",
				reclaimable      = true,
				reclaimTime      = 1200,
				seqnamereclamate = "TREE1RECLAMATE",
				world            = "All Worlds",
			},
			HEAP      = {
				description      = "Debris",
				blocking         = false,
				category         = "heaps",
				damage           = 6400,
				energy           = 0,
				featurereclamate = "SMUDGE01",
				footprintX       = 2,
				footprintZ       = 2,
				hitdensity       = "100",
				metal            = 600,
				object           = "debris2x2c.s3o",
				reclaimable      = true,
				reclaimTime      = 600,
				seqnamereclamate = "TREE1RECLAMATE",
				world            = "All Worlds",
			},
		},
	}
}